---
title: "modelisation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r warning = FALSE}
library(modvarsel)
library(mfe)
```

```{r}
data <- as.matrix(read.csv('../data/indicateurs.csv', header = TRUE, sep = ';', dec = ','))
```

```{r }
# #script R pour creer les modeles
# choiceModels <- list()
# PI = list(EI = 1:3,
#           QC = 4:10,
#           QN = 11:17,
#           QS = 18:24)
# 
# for (i in 1:24){
#   if (i %in% PI$EI){
#     res <- choicemod(X = data[,-PI$EI], Y = data[, i], method = c("linreg", "sir", "rf", "plsr", "ridge"), N = 50, nperm = 100)
#   }
# 
#   if (i %in% PI$EI){
#     res <- choicemod(X = data[,-PI$EI], Y = data[, i], method = c("linreg", "sir", "rf", "plsr", "ridge"), N = 50, nperm = 100)
#   }
# 
#   if (i %in% PI$EI){
#     res <- choicemod(X = data[,-PI$EI], Y = data[, i], method = c("linreg", "sir", "rf", "plsr", "ridge"), N = 50, nperm = 100)
#   }
# 
#   if (i %in% PI$EI){
#     res <- choicemod(X = data[,-PI$EI], Y = data[, i], method = c("linreg", "sir", "rf", "plsr", "ridge"), N = 50, nperm = 100)
#   }
#   choiceModels[[i]] <- res
#   save(choiceModels, file = '../data/choiceModels2.RData')
# }
```

```{r }
#select and save the model in a list
set.seed(123)
load('../data/choiceModelsFinal.RData')
models <- list()

for (i in 1:24){
  #load modeles
  Ylabel <- colnames(data)[i]
  print(paste('Etude des modeles de prediction de:', Ylabel, sep = ' '))
  head(choiceModels[[i]]$mse)
  head(choiceModels[[i]]$mse_all)
  head(choiceModels[[i]]$r2)
  
  #selection of the best model on the R2
  perf_moy <- apply(X = choiceModels[[i]]$mse, MARGIN = 2, FUN = mean, na.rm = TRUE)
  sel_model <-  which(perf_moy == min(perf_moy))
  
  #plot the best method ----
  #RMSE
  boxplot(choiceModels[[i]], method = c("linreg", "sir", 'rf', "plsr", "ridge"), 
          type = "both", col = rgb(0,1,0,0.2), las = 2,
          main = "N = 50 replications")
  
  
  
  ######plot the variables selected for each model ----
  ##linreg
  #varaible selected
  barplot(choiceModels[[i]], method="linreg", type="varsel", las = 2, 
          main = "linreg", col = rgb(1,1,0,0.2))
  
  #total use of each variable in all the simulation
  barplot(choiceModels[[i]], method="linreg", type="sizemod", las = 2, 
          main = "linreg", col = rgb(0,1,1,0.2))
  
  ##sir
  #varaible selected
  barplot(choiceModels[[i]], method="sir", type="varsel", las = 2, 
          main = "sir", col = rgb(1,1,0,0.2))
  
  #total use of each variable in all the simulation
  barplot(choiceModels[[i]], method="sir", type="sizemod", las = 2, 
          main = "sir", col = rgb(0,1,1,0.2))
  
  ##rf
  #varaible selected
  barplot(choiceModels[[i]], method="rf", type="varsel", las = 2, 
          main = "rf", col = rgb(1,1,0,0.2))
  
  #total use of each variable in all the simulation
  barplot(choiceModels[[i]], method="rf", type="sizemod", las = 2, 
          main = "rf", col = rgb(0,1,1,0.2))
  
  ##plsr
  #varaible selected
  barplot(choiceModels[[i]], method="plsr", type="varsel", las = 2, 
          main = "plsr", col = rgb(1,1,0,0.2))
  
  #total use of each variable in all the simulation
  barplot(choiceModels[[i]], method="plsr", type="sizemod", las = 2, 
          main = "plsr", col = rgb(0,1,1,0.2))
  
  ##ridge
  #varaible selected
  barplot(choiceModels[[i]], method="ridge", type="varsel", las = 2, 
          main = "ridge", col = rgb(1,1,0,0.2))
  
  #total use of each variable in all the simulation
  barplot(choiceModels[[i]], method="ridge", type="sizemod", las = 2, 
          main = "ridge", col = rgb(0,1,1,0.2))
  
    #Selection of the variable with the importance
  Y <- data[, i]
  X <- data[,which(colnames(data) %in% rownames(choiceModels[[i]]$pvarsel))]
  methode <- c('linreg', 'sir', 'rf', 'plsr', 'ridge')[sel_model]
  print(paste('choix methode:', methode, sep = ' '))
  
  #etude de l'importance des variables
  imp <- varimportance(X = X, Y = Y, method = methode, nperm = 100)
  meanvi <- colMeans(imp$mat_imp) # mean importance
  knitr::kable(t(meanvi),digits=2)
  knitr::kable(imp$base_imp, digit=2) # baseline value of importance
  
  plot(imp,choice="boxplot", col="lightgreen")
  plot(imp,choice="meanplot", cutoff = TRUE)
  
  
  sel <- which(colnames(data) %in% select(imp, cutoff=TRUE)$var)
  Xnew <- data[, sel]

  
  #model final -----
  if (methode == 'linreg'){
    
    models[[i]] <- reg_lm(X = Xnew, Y = Y, Ylabel = Ylabel)

    print(summary(models[[i]]))
    
    #prediction of the input data
    y_pred <- predict(models[[i]], Xnew)
    
  }
  
  if (methode == 'sir'){
    
    models[[i]] <- sir(X = Xnew, Y = Y, Ylabel = Ylabel)
    
    #visualize ebouli plot
    plot(models[[i]], choice = 'eigenValue')
   
    #visualize the performance of the non-parametric estimation
    plot(models[[i]], choice = 'smoothing')
    
    # Prediction of the input data
    y_pred <- predict(models[[i]], Xnew)
    
  
  }
  
  if (methode == 'rf'){
    
    models[[i]] <- rf(X = Xnew, Y = Y, Ylabel = Ylabel)
    
    #prediction of the input data
    y_pred <- predict(models[[i]], Xnew)
    
 
  }
  
  if (methode == 'ridge'){
    
    models[[i]] <- ridge(X = Xnew, Y = Y, Ylabel = Ylabel)

    print(summary(models[[i]]))
    
    #prediction of the input data
    y_pred <- predict(models[[i]], Xnew)
    
  }
}

# save(models, file = '../data/models2.RData')


#add under models
for (i in 1:length(models)){
  if (class(models[[i]]) == 'reg_lm')  models[[i]]$all_models <- underModels.reg_lm(models[[i]], B = 100)
  
  if (class(models[[i]]) == 'rf')  models[[i]]$all_models <- underModels.rf(models[[i]], B = 100)
  
  if (class(models[[i]]) == 'sir')  models[[i]]$all_models <- underModels.sir(models[[i]], B = 100)
  
  if (class(models[[i]]) == 'ridge')  models[[i]]$all_models <- underModels.ridge(models[[i]], B = 100)
  
  if (class(models[[i]]) == 'pls_reg')  models[[i]]$all_models <- underModels.pls_reg(models[[i]], B = 100)
}


save(models, file = '../data/modelsFifi.RData')
```
